version: '3.9'

services:
  express:
    build: .
    container_name: express-app
    ports:
      - "3001:3001"

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./public_html:/usr/share/nginx/html/doc
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
    depends_on:
      - express
