version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: group-tasker-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
